### PR TITLE
Use wildcard targets

### PR DESCRIPTION
**Pull request by anderseknert**
This wasn't possible before, but now it is:
https://aws.amazon.com/about-aws/whats-new/2022/12/target-multiple-resources-wildcard-configuration-aws-cloudformation-hooks/

Signed-off-by: Anders Eknert <anders@eknert.com>

### CODE REVIEW

**Review by pauly4it — APPROVED** [review]
Nice! Big improvement to the hook config. It'll help reduce the size of the config file below the config file size limit in CloudFormation.

**Comment by PatMyron** [comment]
Why not just one `"*"` instead of listing every `"AWS::SERVICE::*"`? Then you don't need to continue running this cronjob and re-registering hooks

**Comment by pauly4it** [comment]
@PatMyron great question. The CloudFormation Hook docs aren't clear on the full scope of the wildcard support. The docs state that the wildcard functionality supports `AWS::Service::*` and supports `AWS::*::Resource*`, but they don't state if `AWS::*::*` is supported. That's something we'll need to test. In the meantime, the change in this PR significantly simplifies the hook configuration.

**Comment by anderseknert** [comment]
@PatMyron a single wildcard is enough to cover all resources? That'd be great if so!

**Comment by PatMyron** [comment]
Shouldn't need more than one targetName to cover all resource types

**Comment by anderseknert** [comment]
That certainly wasn't made clear in the [docs](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/hooks-structure.html#wildcard-hook-targets). Did you try it and find it working?

**Pull request merged**
